
#Pathes to the data files
training_data_path = 'C:/Users/liort/OneDrive/שולחן העבודה/Exercise/data project/ctr_dataset_train.csv'
test_data_path = 'C:/Users/liort/OneDrive/שולחן העבודה/Exercise/data project/ctr_dataset_test.csv'
clustering_data_path = 'C:/Users/liort/OneDrive/שולחן העבודה/Exercise/data project/ctr_dataset_train.csv'

binary_columns = ['clicked',
                    'app_cat_art_and_design',
                    'app_cat_auto_and_vehicles',
                    'app_cat_beauty',
                    'app_cat_books_and_reference',
                    'app_cat_business',
                    'app_cat_comics',
                    'app_cat_communication',
                    'app_cat_dating',
                    'app_cat_education',
                    'app_cat_entertainment',
                    'app_cat_events',
                    'app_cat_finance',
                    'app_cat_food_and_drink',
                    'app_cat_games - action',
                    'app_cat_games - adventure',
                    'app_cat_games - arcade',
                    'app_cat_games - board',
                    'app_cat_games - card',
                    'app_cat_games - casino',
                    'app_cat_games - casual',
                    'app_cat_games - educational',
                    'app_cat_games - music',
                    'app_cat_games - puzzle',
                    'app_cat_games - racing',
                    'app_cat_games - role_playing',
                    'app_cat_games - simulation',
                    'app_cat_games - sports',
                    'app_cat_games - strategy',
                    'app_cat_games - trivia',
                    'app_cat_games - word',
                    'app_cat_health_and_fitness',
                    'app_cat_libraries_and_demo',
                    'app_cat_lifestyle',
                    'app_cat_music_and_audio',
                    'app_cat_news_and_magazines',
                    'app_cat_personalization',
                    'app_cat_photography',
                    'app_cat_productivity', 
                    'app_cat_shopping',
                    'app_cat_social',
                    'app_cat_sports',
                    'app_cat_tools',
                    'app_cat_travel_and_local',
                    'app_cat_unknown',
                    'app_cat_video_players',
                    'app_cat_weather',
                    'banner_pos_bottom',
                    'banner_pos_bottom-left',
                    'banner_pos_bottom-right',
                    'banner_pos_center',
                    'banner_pos_left',
                    'banner_pos_right',
                    'banner_pos_top',
                    'banner_pos_top-left',
                    'banner_pos_top-right',
                    'device_version_1.1.0',
                    'device_version_3.5.4',
                    'device_version_6.0',
                    'device_version_6.0.1',
                    'device_version_6.1',
                    'device_version_7.0',
                    'device_version_7.1',
                    'device_version_7.1.1',
                    'device_version_7.1.2',
                    'device_version_8.0',
                    'device_version_8.0.0',
                    'device_version_8.0.1',
                    'device_version_8.1.0',
                    'device_version_9',
                    'device_version_O',    
                ]